disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - nesting
  - trailing_comma
  - mark
  - large_tuple
  - private_over_fileprivate
  # SourceKit bug hotfix (otherwise swiftlint 0.35.0 or lover will crash on Xcode 11)
  - no_space_in_method_call
  - trailing_closure
  - reduce_into
opt_in_rules: # some rules are only opt-in
  - closing_brace
  - colon
  - control_statement
  - empty_parameters
  - force_cast
  - force_try
  # - force_unwrapping
  - function_body_length
  - identical_operands
  - identifier_name
  - implicit_getter
  - legacy_random
  - line_length
  - comma
  # - multiline_function_chains # SourceKit bug hotfix (otherwise swiftlint 0.35.0 or lover will crash on Xcode 11)
  - multiline_parameters
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - statement_position
  - syntactic_sugar
  - trailing_semicolon
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - void_return

  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - TestProjectApp
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - TestProjectApp/Resources/Storyboards.swift
  - TestProjectApp/Resources/Strings.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array
type_body_length:
  warning: 300
  error: 500
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - vc
    - ok
trailing_semicolon:
  severity: error
function_body_length:
  warning: 80
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)